name: Ruby CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.4
    - name: Install dependencies
      run: |
        bundle
    - name: Run rspec
      run: bundle exec rspec ./ruby/spec
